#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#BASC_CONFIG FILE


instance:
    proc_mem: [3,6]
    roi_mask_file: '/Users/aki.nikolaidis/Google Drive/DropboxArchive/UIUC_Projects/FYP/MNI152_T1_2mm_brain.nii.gz'
    dataset_bootstraps: 5
    timeseries_bootstraps: 5
    n_clusters: 400
    output_size: 10000
    bootstrap_list: list(range(0,dataset_bootstraps))
    cross_cluster: False
    affinity_threshold: [0.8, 0.8]
    out_dir: '/Users/aki.nikolaidis'
    run: True

    
   
    
    