# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.6
  - 3.5
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
#  - pip install -U tox-travis
  - pip install -r requirements.txt
  - python setup.py install

# command to run tests, e.g. python setup.py test
script: 
#  - tox
#  - python setup.py test
   - pytest
