# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
#  - pip install -U tox-travis
  - pip install -r requirements.txt
  - python setup.py install

# command to run tests, e.g. python setup.py test
script: 
#   - tox
   - travis_wait 60 pytest tests/test_graphestimation.py -s
   - pytest tests/test_nodemaker.py -s
   - pytest tests/test_plotting.py -s
   - pytest tests/test_thresholding.py -s
